super_config:
  pypower_case_name: case14
  baseMVA: 100
grid_config:
  bus:
    BS:
      format: absolute
      value:
      - 0.0
    GS:
      format: absolute
      value:
      - 0.0
  gen:
    PMAX:
      format: absolute
      value:
      - 160
      - 140
      - 100
      - 120
      - 150
    PMIN:
      format: relative
      value:
      - 0.1
      relative_to:
        sheet: gen
        column: PMAX
        map_by: row
    RAMP_UP:
      format: absolute
      value:
      - 40
      - 35
      - 25
      - 30
      - 37.5
    RAMP_DOWN:
      format: absolute
      value:
      - 80
      - 70
      - 50
      - 60
      - 75
    RAMP_STARTUP:
      format: absolute
      value:
      - 80
      - 70
      - 50
      - 60
      - 75
    RAMP_SHUTDOWN:
      format: absolute
      value:
      - 80
      - 70
      - 50
      - 60
      - 75
    RAMP_UP_RD:
      format: absolute
      value:
      - 16
      - 14
      - 10
      - 12
      - 15
    RAMP_DOWN_RD:
      format: absolute
      value:
      - 40
      - 35
      - 25
      - 30
      - 37.5
    MIN_ON_TIME:
      format: absolute
      value:
      - 5
    MIN_OFF_TIME:
      format: absolute
      value:
      - 2
    COST_STARTUP:
      format: absolute
      value:
      - 60
      - 40
      - 50
      - 30
      - 25
    COST_SHUTDOWN:
      format: absolute
      value:
      - 10
      - 15
      - 5
      - 17
      - 8
    COST_SECOND:
      format: absolute
      value:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    COST_FIRST:
      format: absolute
      value:
      - 3
      - 1
      - 6
      - 4
      - 5
    COST_ZERO:
      format: absolute
      value:
      - 20
      - 30
      - 40
      - 18
      - 48
    COST_STORAGE:
      format: absolute
      value:
      - 20.0
      - 15.0
      - 40.0
      - 30.0
      - 35.0
    COST_RD_UP:
      format: absolute
      value:
      - 26
      - 20
      - 24
      - 16
      - 20
    COST_RD_DOWN:
      format: absolute
      value:
      - 10
      - 2
      - 9
      - 6
      - 8
  branch:
    TAP:
      format: absolute
      value:
      - 0.0
    SHIFT:
      format: absolute
      value:
      - 0.0
    BR_B:
      format: absolute
      value:
      - 0.0
    RATE_A:
      format: absolute
      value:
      - 130.3097734383326
      - 64.1442333717417
      - 130.26023474300433
      - 61.166876385556556
      - 48.13292922887795
      - 103.57982926711709
      - 90.06181033993072
      - 66.78108966701933
      - 24.503616924679253
      - 62.53536899236958
      - 40.4238514678819
      - 17.8580050094832
      - 42.37584802178161
      - 156.81855720094887
      - 118.32643119022588
      - 32.954190005499576
      - 33.91572504128086
      - 36.44927022236042
      - 10.0
      - 33.01363503268947
  solar:
    BUS_IDX:
      format: absolute
      value:
      - 2
      - 8
      group: renewable
      remove_gen: true
    PMAX:
      format: relative
      value:
      - 1.0
      relative_to:
        sheet: gen
        column: PMAX
        map_by: bus_idx
    CURTAIL_COST:
      format: relative
      relative_to:
        sheet: gen
        column: COST_FIRST
        aggregate: max
      random_ratio: 0.2
      value:
      - 10
  wind:
    BUS_IDX:
      format: relative
      value:
      - 0.3
      relative_to:
        bus_type:
        - 2
      group: renewable
      remove_gen: true
    PMAX:
      format: relative
      value:
      - 1.0
      relative_to:
        sheet: gen
        column: PMAX
        map_by: bus_idx
    CURTAIL_COST:
      format: relative
      relative_to:
        sheet: gen
        column: COST_FIRST
        aggregate: max
      random_ratio: 0.2
      value:
      - 10.0
  load:
    BUS_IDX:
      format: relative
      value:
      - 1
      relative_to:
        bus_type:
        - 4
    PMAX:
      format: relative
      value:
      - 1.0
      relative_to:
        sheet: bus
        column: PD
        map_by: bus_idx
    SHED_COST:
      format: absolute
      random_ratio: 0.2
      value:
      - 100.0
rescale:
- name: load_to_active_supply_ratio
  target:
    sheet: load
    column: PMAX
    aggregate: sum
    filter:
      STATUS: 1
  ratio: 0.9
  sources:
  - sheet: gen
    column: PMAX
    aggregate: sum
    filter:
      STATUS: 1
  - sheet: solar
    column: PMAX
    aggregate: sum
    filter:
      STATUS: 1
  - sheet: wind
    column: PMAX
    aggregate: sum
    filter:
      STATUS: 1
