super_config:
  pypower_case_name: case14
  baseMVA: 100
grid_config:
  bus:
    BS:
      format: absolute
      value:
      - 0.0
    GS:
      format: absolute
      value:
      - 0.0
  gen:
    PMAX:
      format: absolute
      value:
      - 160
      - 140
      - 100
      - 120
      - 150
    PMIN:
      format: relative
      value:
      - 0.1
      relative_to:
        sheet: gen
        column: PMAX
        map_by: row
    RAMP_UP:
      format: absolute
      value:
      - 40
      - 35
      - 25
      - 30
      - 37.5
    RAMP_DOWN:
      format: absolute
      value:
      - 80
      - 70
      - 50
      - 60
      - 75
    RAMP_STARTUP:
      format: absolute
      value:
      - 80
      - 70
      - 50
      - 60
      - 75
    RAMP_SHUTDOWN:
      format: absolute
      value:
      - 80
      - 70
      - 50
      - 60
      - 75
    RAMP_UP_RD:
      format: absolute
      value:
      - 16
      - 14
      - 10
      - 12
      - 15
    RAMP_DOWN_RD:
      format: absolute
      value:
      - 40
      - 35
      - 25
      - 30
      - 37.5
    MIN_ON_TIME:
      format: absolute
      value:
      - 5
    MIN_OFF_TIME:
      format: absolute
      value:
      - 2
    COST_STARTUP:
      format: absolute
      value:
      - 60
      - 40
      - 50
      - 30
      - 25
    COST_SHUTDOWN:
      format: absolute
      value:
      - 10
      - 15
      - 5
      - 17
      - 8
    COST_SECOND:
      format: absolute
      value:
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
    COST_FIRST:
      format: absolute
      value:
      - 3
      - 1
      - 6
      - 4
      - 5
    COST_ZERO:
      format: absolute
      value:
      - 20
      - 30
      - 40
      - 18
      - 48
    COST_STORAGE:
      format: absolute
      value:
      - 20.0
      - 15.0
      - 40.0
      - 30.0
      - 35.0
    COST_RD_UP:
      format: absolute
      value:
      - 26
      - 20
      - 24
      - 16
      - 20
    COST_RD_DOWN:
      format: absolute
      value:
      - 10
      - 2
      - 9
      - 6
      - 8
  branch:
    TAP:
      format: absolute
      value:
      - 0.0
    SHIFT:
      format: absolute
      value:
      - 0.0
    BR_B:
      format: absolute
      value:
      - 0.0
    RATE_A:
      format: absolute
      value:
      - 129.4229440691038
      - 64.61773381230594
      - 124.50425331060464
      - 63.300314006412705
      - 48.85418025546216
      - 96.86761523452502
      - 93.3379405436764
      - 57.69904988413388
      - 30.124549880778158
      - 64.54614650388923
      - 41.23767059326343
      - 18.27965637516219
      - 43.97525691030005
      - 156.81855720094887
      - 118.83377185207533
      - 31.783743858443692
      - 34.02627400550421
      - 36.2900012255455
      - 10.0
      - 33.61053164114362
  solar:
    BUS_IDX:
      format: absolute
      value:
      - 2
      - 8
      group: renewable
      remove_gen: true
    PMAX:
      format: relative
      value:
      - 1.0
      relative_to:
        sheet: gen
        column: PMAX
        map_by: bus_idx
    CURTAIL_COST:
      format: relative
      relative_to:
        sheet: gen
        column: COST_FIRST
        aggregate: max
      random_ratio: 0.2
      value:
      - 10
  wind:
    BUS_IDX:
      format: relative
      value:
      - 0.3
      relative_to:
        bus_type:
        - 2
      group: renewable
      remove_gen: true
    PMAX:
      format: relative
      value:
      - 1.0
      relative_to:
        sheet: gen
        column: PMAX
        map_by: bus_idx
    CURTAIL_COST:
      format: relative
      relative_to:
        sheet: gen
        column: COST_FIRST
        aggregate: max
      random_ratio: 0.2
      value:
      - 10.0
  load:
    BUS_IDX:
      format: relative
      value:
      - 1
      relative_to:
        bus_type:
        - 4
    PMAX:
      format: relative
      value:
      - 1.0
      relative_to:
        sheet: bus
        column: PD
        map_by: bus_idx
    SHED_COST:
      format: absolute
      random_ratio: 0.2
      value:
      - 100.0
rescale:
  load_to_active_supply_ratio:
    target:
      sheet: load
      column: PMAX
      aggregate: sum
      filter:
        STATUS: 1
    ratio: 0.9
    sources:
      gen:
        sheet: gen
        column: PMAX
        aggregate: sum
        filter:
          STATUS: 1
      solar:
        sheet: solar
        column: PMAX
        aggregate: sum
        filter:
          STATUS: 1
      wind:
        sheet: wind
        column: PMAX
        aggregate: sum
        filter:
          STATUS: 1
